In [1]:
import pandas as pd
import numpy as np

In [2]:
import sklearn.ensemble
import coniferest.isoforest
from coniferest.datasets import MalanchevDataset

# 1e6 data points
dataset = MalanchevDataset(inliers=2**20, outliers=2**6)

# %%time
isoforest = coniferest.isoforest.IsolationForest(n_subsamples=1024)
isoforest.fit(dataset.data)
scores = isoforest.score_samples(dataset.data)
# CPU times: user 16.4 s, sys: 26.1 ms, total: 16.4 s
# Wall time: 5.03 s

# %%time
skforest = sklearn.ensemble.IsolationForest(max_samples=1024)
skforest.fit(dataset.data)
skscores = skforest.score_samples(dataset.data)
# CPU times: user 32.3 s, sys: 4.48 s, total: 36.8 s
# Wall time: 36.8 s

In [3]:
dataset.data

array([[ 0.31848084,  0.13489336],
       [ 0.02048676,  0.00826382],
       [ 0.40663512,  0.45637779],
       ...,
       [ 0.98386354,  0.10997129],
       [ 0.88637551, -0.02969402],
       [ 1.17984907,  0.02029514]])

In [3]:
df=pd.read_csv(r"train.csv",index_col='PassengerId')

In [4]:
df=df[['Pclass','Sex','Age','SibSp','Parch','Fare','Embarked','Survived']]


In [5]:
for colname in df.select_dtypes("object"):
    df[colname], _ = df[colname].factorize()


In [6]:
df['Age']=df['Age'].fillna(df['Age'].mean())

In [7]:
df

Pclass  Sex        Age  SibSp  Parch     Fare  Embarked  Survived
PassengerId                                                                   
1                 3    0  22.000000      1      0   7.2500         0         0
2                 1    1  38.000000      1      0  71.2833         1         1
3                 3    1  26.000000      0      0   7.9250         0         1
4                 1    1  35.000000      1      0  53.1000         0         1
5                 3    0  35.000000      0      0   8.0500         0         0
...             ...  ...        ...    ...    ...      ...       ...       ...
887               2    0  27.000000      0      0  13.0000         0         0
888               1    1  19.000000      0      0  30.0000         0         1
889               3    1  29.699118      1      2  23.4500         0         0
890               1    0  26.000000      0      0  30.0000         1         1
891               3    0  32.000000      0      0   7.7500         2         0

[891 rows x 8 columns]

In [8]:
df.to_numpy()

array([[ 3.        ,  0.        , 22.        , ...,  7.25      ,
         0.        ,  0.        ],
       [ 1.        ,  1.        , 38.        , ..., 71.2833    ,
         1.        ,  1.        ],
       [ 3.        ,  1.        , 26.        , ...,  7.925     ,
         0.        ,  1.        ],
       ...,
       [ 3.        ,  1.        , 29.69911765, ..., 23.45      ,
         0.        ,  0.        ],
       [ 1.        ,  0.        , 26.        , ..., 30.        ,
         1.        ,  1.        ],
       [ 3.        ,  0.        , 32.        , ...,  7.75      ,
         2.        ,  0.        ]])

In [9]:
import sklearn.ensemble
import coniferest.isoforest
from coniferest.datasets import MalanchevDataset

# 1e6 data points
dataset = df.to_numpy()

# %%time
isoforest = coniferest.isoforest.IsolationForest(n_subsamples=1024)
isoforest.fit(dataset)
scores = isoforest.score_samples(dataset)
# CPU times: user 16.4 s, sys: 26.1 ms, total: 16.4 s
# Wall time: 5.03 s

# %%time
skforest = sklearn.ensemble.IsolationForest(max_samples=1024)
skforest.fit(dataset)
skscores = skforest.score_samples(dataset)
# CPU times: user 32.3 s, sys: 4.48 s, total: 36.8 s
# Wall time: 36.8 s

c:\Python310\lib\site-packages\coniferest\coniferest.py:91: UserWarning: population should be greater or equal that subsamples number, got n_population < n_subsamples (891 < 1024), assuming n_subsamples = 891
  warn(msg1 + ', ' + msg2 + ', ' + msg3)
c:\Python310\lib\site-packages\sklearn\ensemble\_iforest.py:288: UserWarning: max_samples (1024) is greater than the total number of samples (891). max_samples will be set to n_samples for estimation.
  warn(


In [10]:
skscores

array([-0.39840377, -0.45742645, -0.42605415, -0.4467257 , -0.35536933,
       -0.40878074, -0.45833661, -0.53428998, -0.473011  , -0.51219088,
       -0.4895724 , -0.49164669, -0.3509829 , -0.5934927 , -0.44571046,
       -0.48010126, -0.61493604, -0.45530247, -0.44569551, -0.45545644,
       -0.39770008, -0.45731171, -0.51071478, -0.44954506, -0.51972486,
       -0.61269409, -0.38342658, -0.67481936, -0.45393059, -0.34474607,
       -0.45574203, -0.48404336, -0.43696083, -0.45540958, -0.5087307 ,
       -0.47451072, -0.45266298, -0.35016735, -0.50698067, -0.49735294,
       -0.47264544, -0.51441361, -0.38333744, -0.57832181, -0.49316479,
       -0.34474607, -0.47551462, -0.43696083, -0.50551233, -0.45622314,
       -0.52706239, -0.35016735, -0.46619394, -0.43792287, -0.55197727,
       -0.44458212, -0.43173784, -0.38866741, -0.49600551, -0.53827208,
       -0.39899748, -0.57574232, -0.49193109, -0.52278786, -0.44572461,
       -0.50862622, -0.41958958, -0.35625737, -0.59498624, -0.44

In [44]:
dataset['score']=scores
dataset['skscores']=skscores

In [45]:
dataset.sort_values(by=['score','skscores'],ascending=True)

Pclass  Sex        Age  SibSp  Parch      Fare  Embarked  \
PassengerId                                                             
439               1    0  64.000000      1      4  263.0000         0   
680               1    0  36.000000      0      1  512.3292         1   
28                1    0  19.000000      3      2  263.0000         0   
886               3    1  39.000000      0      5   29.1250         2   
679               3    1  43.000000      1      6   46.9000         0   
...             ...  ...        ...    ...    ...       ...       ...   
739               3    0  29.699118      0      0    7.8958         0   
740               3    0  29.699118      0      0    7.8958         0   
838               3    0  29.699118      0      0    8.0500         0   
879               3    0  29.699118      0      0    7.8958         0   
815               3    0  30.500000      0      0    8.0500         0   

             Survived    scores  anomaly_score     score  skscores  
PassengerId                                                         
439                 0  0.033026              1 -0.706595 -0.710402  
680                 1  0.000000              1 -0.674588 -0.682905  
28                  0  0.033026              1 -0.669898 -0.674819  
886                 0  0.033026              1 -0.667044 -0.659310  
679                 0  0.033026              1 -0.664005 -0.639631  
...               ...       ...            ...       ...       ...  
739                 0  0.033026              1 -0.352908 -0.344746  
740                 0  0.033026              1 -0.352908 -0.344746  
838                 0  0.033026              1 -0.352908 -0.344746  
879                 0  0.033026              1 -0.352908 -0.344746  
815                 0  0.033026              1 -0.352826 -0.345165  

[891 rows x 12 columns]

In [46]:
dataset

Pclass  Sex        Age  SibSp  Parch     Fare  Embarked  \
PassengerId                                                            
1                 3    0  22.000000      1      0   7.2500         0   
2                 1    1  38.000000      1      0  71.2833         1   
3                 3    1  26.000000      0      0   7.9250         0   
4                 1    1  35.000000      1      0  53.1000         0   
5                 3    0  35.000000      0      0   8.0500         0   
...             ...  ...        ...    ...    ...      ...       ...   
887               2    0  27.000000      0      0  13.0000         0   
888               1    1  19.000000      0      0  30.0000         0   
889               3    1  29.699118      1      2  23.4500         0   
890               1    0  26.000000      0      0  30.0000         1   
891               3    0  32.000000      0      0   7.7500         2   

             Survived    scores  anomaly_score     score  skscores  
PassengerId                                                         
1                   0  0.033026              1 -0.392634 -0.398404  
2                   1  0.000000              1 -0.453400 -0.457426  
3                   1  0.000000              1 -0.431388 -0.426054  
4                   1  0.000000              1 -0.438525 -0.446726  
5                   0  0.033026              1 -0.365732 -0.355369  
...               ...       ...            ...       ...       ...  
887                 0  0.033026              1 -0.385844 -0.384607  
888                 1  0.000000              1 -0.464136 -0.466844  
889                 0  0.033026              1 -0.475091 -0.463630  
890                 1  0.000000              1 -0.473353 -0.474850  
891                 0  0.033026              1 -0.429131 -0.414340  

[891 rows x 12 columns]

In [47]:
# %%time
from coniferest.sklearn.isoforest import IsolationForestEvaluator
dataset = dataset.drop(['score','skscores'],axis=1)
isoforest = sklearn.ensemble.IsolationForest(max_samples='auto',contamination=float(0.2),random_state=10)


isoforest.fit(dataset[['Survived']])
print(isoforest.get_params())

dataset['scores'] = isoforest.decision_function(dataset[['Survived']])

dataset['anomaly_score'] = isoforest.predict(dataset[['Survived']])



# Wall time: 6.32 s

{'bootstrap': False, 'contamination': 0.2, 'max_features': 1.0, 'max_samples': 'auto', 'n_estimators': 100, 'n_jobs': None, 'random_state': 10, 'verbose': 0, 'warm_start': False}


c:\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


In [48]:
dataset[dataset['anomaly_score']==-1] 

Empty DataFrame
Columns: [Pclass, Sex, Age, SibSp, Parch, Fare, Embarked, Survived, scores, anomaly_score]
Index: []